### ISSUE TITLE
[Submission문의] 리더보드 점수 0점 관련

### ISSUE THREAD

**Issue by pnltoen** [reinforcement-learning-kr/2021_RLKR_Drone_Delivery_Challenge_with_Unity#15]
- 팀명 : pnltoen

- 문의자 : 박우진

---
- 문의 내용

Docs의 "학습된 모델 제출하기" 부분을 보고 AIFactory에서 제출완료하였습니다. 
mlagents로 진행하여 .onnx 확장자를 제출하였고 "API call was successful" 또한 확인할 수 있었습니다.
저희 팀에서 제출전에 예상하기로는 고득점을 예상하였는데, 제출 후 0점으로 기입되어서 질문드리게 되었습니다.
![image](https://user-images.githubusercontent.com/85833046/141061487-11bcdba3-f210-4de4-a7e8-f0229f63bce5.png)
챕쳐한 로그파일입니다! 바쁘시겠지만 해결방안을 공유해주신다면 정말 감사하겠습니다!

**Comment by Kyushik** [comment]
지금 환경 수정했습니다! 확인 부탁드립니다! @pnltoen
