### ISSUE TITLE
[Submission문의] Grading Fail

### ISSUE THREAD

**Issue by Joovvhan** [reinforcement-learning-kr/2021_RLKR_Drone_Delivery_Challenge_with_Unity#16]
- 팀명 : S1

- 문의자 : 송주환

---
- 문의 내용
안녕하세요, 학습된 onnx 파일을 제출되었는데, 제출 이력은 있으나 다음과 같이 Grading이 실패한 상태입니다.
원인이 무엇인지 확인 부탁드립니다.

![image](https://user-images.githubusercontent.com/43201528/141141663-00475316-f512-4fe0-9e1a-8ded243080d3.png)

**Comment by Kyushik** [comment]
아마 저희가 평가를 위한 환경을 잠시 변경하는 사이에 제출을 하신거 아닌가 생각합니다! ㅜㅜ 다시 제출해서 테스트 부탁드립니다!

**Comment by Joovvhan** [comment]
해결되었습니다~ 감사합니다.
