### ISSUE TITLE
[Submission문의] TOO_MANY_TRIALS 이슈

### ISSUE THREAD

**Issue by Joovvhan** [reinforcement-learning-kr/2021_RLKR_Drone_Delivery_Challenge_with_Unity#20]
- 팀명: S1

- 문의자: 송주환

---
- 문의 내용
안녕하세요. 제출 과정에서 다음과 같은 에러 메세지를 확인하였습니다.
하루 동안 3회 제출하였기 때문에 특별히 제출 횟수 규정을 위반하지는 않은 것 같습니다.
원인이 무엇인지 확인 부탁드리겠습니다.

```
Authentication:INFO: Response from auth server: KEY_VALID
Authentication:INFO: Submit key validity checked.
AFAPIClient:INFO: Submission failed.
AFAPIClient:INFO: ==========response from the submission server==========
AFAPIClient:INFO: <Response [200]>
AFAPIClient:INFO: TOO_MANY_TRIALS
AFAPIClient:INFO: ==========response from the submission server==========
AFAPIClient:ERROR: API call Failed.
```

**Comment by Kyushik** [comment]
지금 리더보드 관련해서 처리해주시는 AIFactory에 문의해보았습니다! 현재 제출 및 평가 관련해서 이슈가 조금 있어서 해당 이슈가 끝난 이후로 리더보드를 싹 정리하고 제출 횟수를 초기화 할 예정입니다. 이에 따라 지금 제출한 부분들 때문에 나중에 손해를 보시지 않게 할 예정입니다!

**Comment by Kyushik** [comment]
아 방금 답변 받아서 전달드립니다! 제출의 경우 24시간 안에 5건 제출하는 경우 제출 횟수 규정을 넘는 것으로 확인했습니다! 이번 제출 프로세스가 안정화되면 처리 속도도 향상시켜서 제출횟수도 늘릴 것으로 생각되니 참고 부탁드립니다! 감사합니다

**Comment by Joovvhan** [comment]
답변 감사합니다. 기다렸다가 오늘 추가 다시 제출을 하려고 하는데 같은 결과가 발생했습니다.
현재 시스템 이슈로 제출이 어렵다고 이해됩니다.
해당 이슈가 해결되어 제출이 가능해지는 시점이 언제인지 알려주실 수 있을까요?

**Comment by Kyushik** [comment]
지금 저희가 제출은 가능한데 점수가 제대로 평가되지 않는 문제가 있어 AIFactory쪽에서 제출을 닫은 것이 아닌가 추측됩니다! 이슈와 관련된 원인을 찾은 듯 하여 주말 중에는 꼭 해결을 해보려고 노력중입니다! 관련 문제가 해결되는대로 대회 기간 연장, 제출횟수 초기화, 제출횟수 향상 등을 통해 좀 더 잘 참여하실 수 있는 방향을 검토중에 있습니다!! 참여에 불편을 드려 운영진으로서 정말 죄송하다는 말씀 드립니다!

**Comment by Joovvhan** [comment]
답변 감사합니다. 해당 이슈 해결 공지 기다리도록 하겠습니다.

**Comment by Kyushik** [comment]
현재 onnx 관련 이슈 해결하여 제출 가능합니다! 다시 제출 시도해주시면 감사드리겠습니다! :)
