### ISSUE TITLE
[Submission문의] 11월 26일 시점의 TOO_MANY_TRIALS 이슈

### ISSUE THREAD

**Issue by Joovvhan** [reinforcement-learning-kr/2021_RLKR_Drone_Delivery_Challenge_with_Unity#26]
- 팀명 : S1

- 문의자 : 송주환

---
- 문의 내용
안녕하세요 ml-agents 모델을 제출하는데 TOO_MANY_TRIALS 에러로 인해 제출이 되지 않는 상황입니다.
11월 26일 21시를 넘겨서 제출을 시도하였기 때문에 특별히 제출 횟수 제한을 넘기지는 않은 것 같은데요. 
참고하시라고 지난 이틀 간의 제출 시간 기록을 첨부해드립니다.

![image](https://user-images.githubusercontent.com/43201528/143596403-4942e6a3-90aa-4581-82d3-c8297d4950b0.png)

오늘 순위 변동이 있었기 때문에 모델을 빨리 검증해보고 싶은 관계로 늦은 시간이지만 확인 부탁드립니다!

**Comment by Joovvhan** [comment]
27일 1시에 정상적으로 제출되고 있습니다! 일시적인 문제였던 것 같습니다.

**Comment by Kyushik** [comment]
@Joovvhan  네네 안그대로 문제가 있다는 제보들이 있었는데 AIFactory 측에 문의하여 해결된 것 같습니다!
