### ISSUE TITLE
[환경파일문의] Describe Your Issue

### ISSUE THREAD

**Issue by pnltoen** [reinforcement-learning-kr/2021_RLKR_Drone_Delivery_Challenge_with_Unity#6]
- 팀명 : pnltoen

- 문의자 : 박우진

---
- 문의 내용
안녕하세요 RL Korea 담당자님!
다름이 아니오라 학습 실행 시 해상도 오류가 발생하여 질문드리게 되었습니다.
학습 시작전 빌드 파일이 잘 작동하는지 확인하고자 DroneDelivery.exe를 실행했을 때는 정상적으로 큰 화면으로 실행되는 것을 확인하였습니다.
이 후 기본 상태에서 ppo 실행 후 모니터링을 통해 학습 파일을 완성하고자 학습 실행을 누르니 화면이 너무 작아져서 학습이 진행되는 화면을 가시화할 수 없는 상황입니다.
파일도 삭제 후 다시 다운로드해보고, 재부팅을 진행하여도 아래와 같이 너무 작은 화면으로 출력되는데 해당 문제 해결방법을 여쭤볼 수 있을까요?

![image](https://user-images.githubusercontent.com/85833046/139654733-c6553ab8-7112-49a4-ba8f-ac34fa241fe0.png)

전체화면에서 출력되는 크기입니다. 확인 후 해결방법을 알려주신다면 정말 감사하겠습니다!
+) 학습은 정상적으로 진행되는 상황입니다!

**Comment by Kyushik** [comment]
안녕하세요! 유니티 환경의 경우 해상도를 너무 크게하면 유니티 환경 자체의 그래픽 연산을 위해 많이 리소스가 소요될 수 있어서 기본 크기를 작게 설정하였습니다!! 문의 주신 내용은 다른 분들도 많이 질문하실 사항으로 생각하여 다음의 FAQ에 5번 항목으로 답변을 작성하였습니다! 참고 부탁드려요!! 감사합니다! 
https://github.com/reinforcement-learning-kr/2021_RLKR_Drone_Delivery_Challenge_with_Unity/discussions/2

**Comment by pnltoen** [comment]
네네! 확인하였습니다.
슬랙에서 질문 많이드렸는데ㅠㅠ 깃허브에서까지 직접 답변해주셔서 정말 감사합니다!

**Comment by Kyushik** [comment]
아앗 정말 참여해주셨군요 ㅎㅎㅎ 정말 감사합니다! :) 화이팅해서 좋은 결과 있으시길!!!
